title: Nathan's Amazing Website
email: nathanrosspowell@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Hey, I'm a video game professional. 
  This small site outlines my work experience, shares some of my projects and gives you ways to contact me.
  Mostly I have a website as a product of being interesting in webdev every few years or so,
  please don't expect anything amazing.
baseurl: legendary-pancake/ # the subpath of your site, e.g. /blog
url: "https://nathanrosspowell.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: nathanross
github_username:  nathanrosspowell
remote_theme: "dracula/gh-pages"
show_header: true
plugins:
  - jekyll-feed
  - jekyll-seo-tag
sass:
    style: compressed
